import React, { useState } from 'react';
import { Player, SeasonRecord } from '../types';
import {
  Trophy,
  Star,
  Sparkles,
  UserPlus,
  Award,
  Crown,
  Globe,
  Shield,
  Zap,
  CheckCircle2,
  Calendar,
  Flame,
  X,
  Layers,
  BarChart3,
  Medal,
  Activity
} from 'lucide-react';
import { sound } from '../utils/audio';

interface RetirementModalProps {
  player: Player;
  onProceedToChild: () => void;
  onClose?: () => void;
  legacyScore?: number;
}

type SnapshotTab = 'snapshot' | 'highlights' | 'stats';

export const RetirementModal: React.FC<RetirementModalProps> = ({
  player,
  onProceedToChild,
  onClose,
  legacyScore = 0
}) => {
  const [activeTab, setActiveTab] = useState<SnapshotTab>('snapshot');

  // Peak OVR Calculation
  const peakOvr = Math.max(
    player.ovr,
    ...(player.history && player.history.length > 0
      ? player.history.map(h => h.newOvr || h.oldOvr || player.ovr)
      : [player.ovr])
  );

  const startYear = player.history && player.history.length > 0
    ? player.history[0].year
    : player.year - Math.max(0, player.age - 18);
  const endYear = player.year;
  const seasonsCount = player.history && player.history.length > 0
    ? player.history.length
    : Math.max(1, endYear - startYear + 1);

  const isHallOfFame = peakOvr >= 85 || player.ballonDorsWon >= 1;

  // Career Rating Grade
  const getCareerGrade = (): { grade: 'LEGENDARY' | 'S' | 'A' | 'B' | 'C'; color: string; badgeBg: string } => {
    if (peakOvr >= 90 || player.ballonDorsWon >= 2 || (player.totalTrophies >= 8 && player.totalGoals >= 200)) {
      return {
        grade: 'LEGENDARY',
        color: 'text-amber-300',
        badgeBg: 'bg-gradient-to-r from-amber-500/30 via-yellow-500/20 to-amber-500/30 border-amber-400 text-amber-300'
      };
    }
    if (peakOvr >= 85 || player.ballonDorsWon >= 1 || player.totalTrophies >= 4) {
      return {
        grade: 'S',
        color: 'text-purple-400',
        badgeBg: 'bg-purple-500/20 border-purple-400 text-purple-300'
      };
    }
    if (peakOvr >= 80 || player.totalTrophies >= 2 || player.totalGoals >= 100) {
      return {
        grade: 'A',
        color: 'text-[#2ECC71]',
        badgeBg: 'bg-[#2ECC71]/20 border-[#2ECC71]/40 text-[#2ECC71]'
      };
    }
    if (peakOvr >= 75 || player.totalApps >= 250) {
      return {
        grade: 'B',
        color: 'text-cyan-400',
        badgeBg: 'bg-cyan-500/20 border-cyan-400 text-cyan-300'
      };
    }
    return {
      grade: 'C',
      color: 'text-white/70',
      badgeBg: 'bg-white/10 border-white/20 text-white/80'
    };
  };

  const careerGrade = getCareerGrade();

  // Average Rating
  const avgRating = player.history && player.history.length > 0
    ? (player.history.reduce((sum, h) => sum + (h.rating || 7.0), 0) / player.history.length).toFixed(2)
    : player.avgRatingSum && player.totalApps > 0
      ? (player.avgRatingSum / Math.max(1, player.history?.length || 1)).toFixed(2)
      : '7.15';

  // Goals & Assists Ratios
  const goalsPerApp = player.totalApps > 0 ? (player.totalGoals / player.totalApps).toFixed(2) : '0.00';
  const assistsPerApp = player.totalApps > 0 ? (player.totalAssists / player.totalApps).toFixed(2) : '0.00';
  const goalContributions = player.totalGoals + player.totalAssists;

  // Legacy Points Generated by this player
  const playerLegacyPoints =
    (player.totalGoals * 100) +
    (player.totalAssists * 50) +
    (player.totalTrophies * 1500) +
    ((player.intTrophies?.length || 0) * 1500) +
    (player.ballonDorsWon * 5000) +
    (player.goldenShoesWon * 2000) +
    (peakOvr >= 85 ? 2000 : 0) +
    (player.intCaps * 25);

  // Best/Defining Season
  const bestSeason: SeasonRecord | null = player.history && player.history.length > 0
    ? player.history.reduce((best, cur) => {
        const curScore = (cur.goals * 3) + (cur.assists * 2) + (cur.rating * 5) + (cur.trophyWon ? 20 : 0);
        const bestScore = (best.goals * 3) + (best.assists * 2) + (best.rating * 5) + (best.trophyWon ? 20 : 0);
        return curScore > bestScore ? cur : best;
      }, player.history[0])
    : null;

  // Club History Breakdown
  interface ClubTenure {
    clubName: string;
    startYear: number;
    endYear: number;
    seasons: number;
    apps: number;
    goals: number;
    assists: number;
    trophies: string[];
  }

  const clubBreakdown: ClubTenure[] = (player.history || []).reduce((acc: ClubTenure[], season: SeasonRecord) => {
    const existing = acc.find(c => c.clubName === season.club);
    if (existing) {
      existing.seasons += 1;
      existing.apps += season.apps || 0;
      existing.goals += season.goals || 0;
      existing.assists += season.assists || 0;
      if (season.trophyWon && !existing.trophies.includes(season.trophyWon)) {
        existing.trophies.push(season.trophyWon);
      }
      existing.endYear = season.year;
    } else {
      acc.push({
        clubName: season.club,
        startYear: season.year,
        endYear: season.year,
        seasons: 1,
        apps: season.apps || 0,
        goals: season.goals || 0,
        assists: season.assists || 0,
        trophies: season.trophyWon ? [season.trophyWon] : []
      });
    }
    return acc;
  }, []);

  // Trophies list
  const clubTrophiesWon = (player.history || [])
    .filter(h => h.trophyWon)
    .map(h => ({
      year: h.year,
      club: h.club,
      trophy: h.trophyWon!
    }));

  const allTrophiesCount = player.totalTrophies + (player.intTrophies?.length || 0);

  // Dynamic Milestone Badges
  const milestones: { label: string; icon: string; desc: string; color: string }[] = [];
  if (player.ballonDorsWon > 0) {
    milestones.push({
      label: `${player.ballonDorsWon}x Ballon d'Or Winner`,
      icon: '👑',
      desc: 'Crowned the absolute best footballer on the planet',
      color: 'border-[#F1C40F]/40 bg-[#F1C40F]/10 text-[#F1C40F]'
    });
  }
  if (player.goldenShoesWon > 0) {
    milestones.push({
      label: `${player.goldenShoesWon}x Golden Boot Winner`,
      icon: '👟',
      desc: 'Top continental goalscorer award winner',
      color: 'border-amber-500/40 bg-amber-500/10 text-amber-300'
    });
  }
  if (isHallOfFame) {
    milestones.push({
      label: 'Hall of Fame Immortal',
      icon: '⭐',
      desc: 'Inducted into world football immortality',
      color: 'border-[#F1C40F]/40 bg-[#F1C40F]/10 text-[#F1C40F]'
    });
  }
  if (peakOvr >= 88) {
    milestones.push({
      label: `Peak ${peakOvr} OVR World Class`,
      icon: '💎',
      desc: 'Reached the pinnacle of footballing excellence',
      color: 'border-cyan-500/40 bg-cyan-500/10 text-cyan-300'
    });
  }
  if (player.totalGoals >= 200) {
    milestones.push({
      label: 'Double Centurion (200+ Goals)',
      icon: '⚡',
      desc: `${player.totalGoals} career club goals scored`,
      color: 'border-[#2ECC71]/40 bg-[#2ECC71]/10 text-[#2ECC71]'
    });
  } else if (player.totalGoals >= 100) {
    milestones.push({
      label: 'Centurion (100+ Goals)',
      icon: '⚽',
      desc: `${player.totalGoals} career club goals scored`,
      color: 'border-[#2ECC71]/40 bg-[#2ECC71]/10 text-[#2ECC71]'
    });
  }
  if (player.totalApps >= 400) {
    milestones.push({
      label: 'Iron Man (400+ Appearances)',
      icon: '🛡️',
      desc: `${player.totalApps} official club appearances`,
      color: 'border-blue-500/40 bg-blue-500/10 text-blue-300'
    });
  }
  if (allTrophiesCount >= 5) {
    milestones.push({
      label: `Serial Champion (${allTrophiesCount} Silverware)`,
      icon: '🏆',
      desc: 'Won major club & international silverware',
      color: 'border-yellow-400/40 bg-yellow-400/10 text-yellow-300'
    });
  }
  if (player.isCaptain) {
    milestones.push({
      label: `${player.nationality} National Captain`,
      icon: '🎖️',
      desc: 'Wore the armband and led nation onto the world stage',
      color: 'border-emerald-500/40 bg-emerald-500/10 text-emerald-300'
    });
  }
  if (player.intCaps >= 50) {
    milestones.push({
      label: `International Centurion / Veteran (${player.intCaps} Caps)`,
      icon: '🌍',
      desc: `Represented ${player.nationality} on the international stage`,
      color: 'border-cyan-400/40 bg-cyan-400/10 text-cyan-300'
    });
  }
  if (clubBreakdown.length === 1 && seasonsCount >= 4) {
    milestones.push({
      label: `One-Club Legend (${player.club})`,
      icon: '❤️',
      desc: `Devoted entire career exclusively to ${player.club}`,
      color: 'border-rose-500/40 bg-rose-500/10 text-rose-300'
    });
  } else if (clubBreakdown.length >= 3) {
    milestones.push({
      label: `Journeyman Veteran (${clubBreakdown.length} Clubs)`,
      icon: '✈️',
      desc: 'Conquered multiple clubs and football cultures',
      color: 'border-indigo-400/40 bg-indigo-400/10 text-indigo-300'
    });
  }

  const handleProceed = () => {
    sound.playTrophyFanfare();
    onProceedToChild();
  };

  return (
    <div className="fixed inset-0 bg-black/90 backdrop-blur-md z-50 flex items-center justify-center p-3 overflow-y-auto">
      <div className="bg-[#1E1E1E] border border-[#F1C40F]/40 rounded-3xl w-full max-w-lg p-4 sm:p-5 text-white space-y-4 shadow-2xl my-auto max-h-[92vh] flex flex-col">
        
        {/* TOP HEADER */}
        <div className="relative border-b border-white/10 pb-3 shrink-0">
          {onClose && (
            <button
              onClick={onClose}
              className="absolute -top-1 -right-1 p-1.5 text-white/40 hover:text-white rounded-full bg-white/5 hover:bg-white/10 transition-colors"
              title="Close & Review"
            >
              <X className="w-4 h-4" />
            </button>
          )}

          <div className="text-center space-y-1">
            <div className="inline-flex items-center space-x-1.5 px-3 py-1 rounded-full bg-[#F1C40F]/15 border border-[#F1C40F]/40 text-[#F1C40F] text-[10px] font-extrabold uppercase tracking-widest font-mono">
              <Crown className="w-3.5 h-3.5 fill-current" />
              <span>LEGACY SNAPSHOT • RETIREMENT</span>
            </div>

            <h2 className="text-2xl font-black italic font-serif tracking-tight text-white mt-1">
              {player.name}
            </h2>

            <div className="flex items-center justify-center space-x-2 text-xs text-white/60">
              <span className="font-semibold text-[#2ECC71]">{player.position}</span>
              <span>•</span>
              <span>{player.nationality}</span>
              <span>•</span>
              <span>Gen {player.generation}</span>
              <span>•</span>
              <span className="font-mono">{startYear} – {endYear} (Age {player.age})</span>
            </div>

            {/* Career Grade & Peak Badges */}
            <div className="pt-2 flex items-center justify-center space-x-2">
              <div className={`px-3 py-1 rounded-xl border text-xs font-black font-mono shadow-sm ${careerGrade.badgeBg}`}>
                CAREER GRADE: {careerGrade.grade}
              </div>
              <div className="bg-[#2A2A2A] px-3 py-1 rounded-xl border border-white/10 text-xs font-black font-mono text-[#F1C40F]">
                PEAK {peakOvr} OVR
              </div>
            </div>
          </div>
        </div>

        {/* 📑 TAB NAVIGATION */}
        <div className="grid grid-cols-3 gap-1 bg-[#2A2A2A] p-1 rounded-xl border border-white/5 text-xs shrink-0">
          <button
            onClick={() => {
              sound.playTap();
              setActiveTab('snapshot');
            }}
            className={`py-2 px-1 rounded-lg font-black uppercase tracking-wider text-[10px] transition-all flex items-center justify-center space-x-1.5 cursor-pointer ${
              activeTab === 'snapshot'
                ? 'bg-[#F1C40F] text-black shadow-md'
                : 'text-white/60 hover:text-white hover:bg-white/5'
            }`}
          >
            <Sparkles className="w-3 h-3" />
            <span>Snapshot</span>
          </button>

          <button
            onClick={() => {
              sound.playTap();
              setActiveTab('highlights');
            }}
            className={`py-2 px-1 rounded-lg font-black uppercase tracking-wider text-[10px] transition-all flex items-center justify-center space-x-1.5 cursor-pointer ${
              activeTab === 'highlights'
                ? 'bg-[#F1C40F] text-black shadow-md'
                : 'text-white/60 hover:text-white hover:bg-white/5'
            }`}
          >
            <Trophy className="w-3 h-3" />
            <span>Highlights</span>
          </button>

          <button
            onClick={() => {
              sound.playTap();
              setActiveTab('stats');
            }}
            className={`py-2 px-1 rounded-lg font-black uppercase tracking-wider text-[10px] transition-all flex items-center justify-center space-x-1.5 cursor-pointer ${
              activeTab === 'stats'
                ? 'bg-[#F1C40F] text-black shadow-md'
                : 'text-white/60 hover:text-white hover:bg-white/5'
            }`}
          >
            <BarChart3 className="w-3 h-3" />
            <span>Final Stats</span>
          </button>
        </div>

        {/* 📦 SCROLLABLE CONTENT BODY */}
        <div className="overflow-y-auto flex-1 pr-0.5 space-y-3.5 text-xs custom-scrollbar min-h-[220px]">
          
          {/* TAB 1: SNAPSHOT OVERVIEW */}
          {activeTab === 'snapshot' && (
            <div className="space-y-3 animate-fade-in">
              {/* 👑 HALL OF FAME HERO CALLOUT */}
              {isHallOfFame ? (
                <div className="bg-gradient-to-r from-[#F1C40F]/20 via-[#F1C40F]/10 to-[#F1C40F]/20 border border-[#F1C40F]/50 p-3 rounded-2xl flex items-center space-x-3 text-xs shadow-lg">
                  <div className="p-2 rounded-xl bg-[#F1C40F]/20 border border-[#F1C40F]/40 text-[#F1C40F] shrink-0">
                    <Star className="w-6 h-6 fill-current" />
                  </div>
                  <div>
                    <div className="font-black text-[#F1C40F] text-sm uppercase tracking-wide flex items-center space-x-1.5">
                      <span>HALL OF FAME INDUCTEE</span>
                      <Crown className="w-3.5 h-3.5 fill-current inline" />
                    </div>
                    <div className="text-[11px] text-white/70 mt-0.5">
                      Earned immortal dynasty status through legendary career milestones and excellence.
                    </div>
                  </div>
                </div>
              ) : (
                <div className="bg-[#2A2A2A] border border-white/5 p-3 rounded-2xl flex items-center space-x-3 text-xs">
                  <Medal className="w-5 h-5 text-emerald-400 shrink-0" />
                  <div>
                    <div className="font-bold text-white text-xs">Honorable Career Veteran</div>
                    <div className="text-[10px] text-white/50">Completed an honorable tenure representing the family lineage.</div>
                  </div>
                </div>
              )}

              {/* 📊 KEY CAREER STATS SUMMARY GRID */}
              <div className="bg-[#2A2A2A] p-3.5 rounded-2xl border border-white/5 space-y-2.5">
                <div className="flex items-center justify-between border-b border-white/5 pb-1.5">
                  <span className="text-[9px] font-black uppercase text-white/40 tracking-widest font-mono">
                    CAREER TOTALS SNAPSHOT
                  </span>
                  <span className="text-[10px] text-[#2ECC71] font-mono font-bold">
                    {seasonsCount} Seasons Played
                  </span>
                </div>

                <div className="grid grid-cols-3 gap-2 text-center font-mono">
                  <div className="bg-[#1E1E1E] p-2 rounded-xl border border-white/5">
                    <span className="text-[9px] uppercase font-bold text-white/40 block">Appearances</span>
                    <span className="font-black text-white text-base mt-0.5 block">{player.totalApps}</span>
                  </div>
                  <div className="bg-[#1E1E1E] p-2 rounded-xl border border-white/5">
                    <span className="text-[9px] uppercase font-bold text-white/40 block">Total Goals</span>
                    <span className="font-black text-[#2ECC71] text-base mt-0.5 block">{player.totalGoals}</span>
                  </div>
                  <div className="bg-[#1E1E1E] p-2 rounded-xl border border-white/5">
                    <span className="text-[9px] uppercase font-bold text-white/40 block">Total Assists</span>
                    <span className="font-black text-cyan-400 text-base mt-0.5 block">{player.totalAssists}</span>
                  </div>

                  <div className="bg-[#1E1E1E] p-2 rounded-xl border border-white/5">
                    <span className="text-[9px] uppercase font-bold text-white/40 block">All Trophies</span>
                    <span className="font-black text-[#F1C40F] text-base mt-0.5 block">{allTrophiesCount} 🏆</span>
                  </div>
                  <div className="bg-[#1E1E1E] p-2 rounded-xl border border-white/5">
                    <span className="text-[9px] uppercase font-bold text-white/40 block">Ballon d'Ors</span>
                    <span className="font-black text-[#F1C40F] text-base mt-0.5 block">{player.ballonDorsWon} 👑</span>
                  </div>
                  <div className="bg-[#1E1E1E] p-2 rounded-xl border border-white/5">
                    <span className="text-[9px] uppercase font-bold text-white/40 block">Avg Rating</span>
                    <span className="font-black text-amber-300 text-base mt-0.5 block">{avgRating}</span>
                  </div>
                </div>
              </div>

              {/* 🌟 DEFINING CAREER SEASON */}
              {bestSeason && (
                <div className="bg-[#2A2A2A] p-3.5 rounded-2xl border border-white/5 space-y-2">
                  <div className="flex items-center justify-between border-b border-white/5 pb-1.5">
                    <div className="flex items-center space-x-1.5 text-xs text-[#F1C40F] font-bold">
                      <Flame className="w-3.5 h-3.5 fill-current" />
                      <span>DEFINING CAREER SEASON</span>
                    </div>
                    <span className="text-[10px] text-white/40 font-mono">Age {bestSeason.age} ({bestSeason.year})</span>
                  </div>

                  <div className="flex items-center justify-between text-xs pt-0.5">
                    <div>
                      <div className="font-extrabold text-white text-sm italic font-serif">{bestSeason.club}</div>
                      <div className="text-[10px] text-white/50">{bestSeason.leagueName || 'Top Flight'}</div>
                    </div>
                    <div className="text-right font-mono">
                      <div className="text-[#2ECC71] font-black text-xs">{bestSeason.goals} Goals • {bestSeason.assists} Ast</div>
                      <div className="text-[10px] text-amber-300 font-bold">{bestSeason.rating.toFixed(2)} Match Rating</div>
                    </div>
                  </div>

                  {bestSeason.trophyWon && (
                    <div className="mt-1 pt-1.5 border-t border-white/5 text-[11px] text-[#F1C40F] flex items-center space-x-1">
                      <span>🏆 Won:</span>
                      <span className="font-bold">{bestSeason.trophyWon}</span>
                    </div>
                  )}
                </div>
              )}

              {/* 🧬 DYNASTY BONUS CONTRIBUTIONS */}
              <div className="bg-gradient-to-br from-[#2A2A2A] to-[#1E1E1E] p-3.5 rounded-2xl border border-[#2ECC71]/30 space-y-2 text-xs">
                <div className="flex items-center justify-between border-b border-white/5 pb-1.5">
                  <div className="flex items-center space-x-1.5 text-[#2ECC71] font-black text-[10px] uppercase tracking-wider">
                    <Sparkles className="w-3.5 h-3.5" />
                    <span>DYNASTY HERITAGE REWARD</span>
                  </div>
                  <span className="font-mono font-bold text-[#2ECC71] text-xs">
                    +{playerLegacyPoints.toLocaleString()} PTS
                  </span>
                </div>
                <p className="text-[11px] text-white/70 leading-relaxed">
                  {player.name}'s achievements pass down directly to enhance family legacy and unlock inherited advantages for Generation {player.generation + 1}.
                </p>
              </div>
            </div>
          )}

          {/* TAB 2: HIGHLIGHTS & ACCOLADES */}
          {activeTab === 'highlights' && (
            <div className="space-y-3 animate-fade-in">
              {/* INDIVIDUAL AWARDS POD */}
              <div className="bg-[#2A2A2A] p-3.5 rounded-2xl border border-white/5 space-y-2.5">
                <div className="flex items-center space-x-1.5 text-xs text-[#F1C40F] font-bold border-b border-white/5 pb-1.5">
                  <Award className="w-3.5 h-3.5" />
                  <span className="text-[10px] uppercase font-black tracking-wider">INDIVIDUAL ACCOLADES & HONOURS</span>
                </div>

                <div className="grid grid-cols-2 gap-2">
                  <div className="bg-[#1E1E1E] p-2.5 rounded-xl border border-white/5 flex items-center space-x-2.5">
                    <div className="p-2 rounded-lg bg-[#F1C40F]/15 text-[#F1C40F]">
                      <Crown className="w-4 h-4 fill-current" />
                    </div>
                    <div>
                      <div className="text-[9px] uppercase font-bold text-white/40">Ballon d'Or</div>
                      <div className="text-sm font-black text-[#F1C40F] font-mono">{player.ballonDorsWon}x Won</div>
                    </div>
                  </div>

                  <div className="bg-[#1E1E1E] p-2.5 rounded-xl border border-white/5 flex items-center space-x-2.5">
                    <div className="p-2 rounded-lg bg-amber-500/15 text-amber-300">
                      <Medal className="w-4 h-4" />
                    </div>
                    <div>
                      <div className="text-[9px] uppercase font-bold text-white/40">Golden Boot</div>
                      <div className="text-sm font-black text-amber-300 font-mono">{player.goldenShoesWon}x Won</div>
                    </div>
                  </div>

                  <div className="bg-[#1E1E1E] p-2.5 rounded-xl border border-white/5 flex items-center space-x-2.5">
                    <div className="p-2 rounded-lg bg-cyan-500/15 text-cyan-300">
                      <Star className="w-4 h-4" />
                    </div>
                    <div>
                      <div className="text-[9px] uppercase font-bold text-white/40">Man of Match</div>
                      <div className="text-sm font-black text-cyan-300 font-mono">{player.motmAwards || 0}x Won</div>
                    </div>
                  </div>

                  <div className="bg-[#1E1E1E] p-2.5 rounded-xl border border-white/5 flex items-center space-x-2.5">
                    <div className="p-2 rounded-lg bg-emerald-500/15 text-emerald-300">
                      <Globe className="w-4 h-4" />
                    </div>
                    <div>
                      <div className="text-[9px] uppercase font-bold text-white/40">Captaincy</div>
                      <div className="text-sm font-black text-emerald-300 font-mono">{player.isCaptain ? 'Captain 👑' : 'Squad Player'}</div>
                    </div>
                  </div>
                </div>
              </div>

              {/* 🏆 TROPHY CABINET */}
              <div className="bg-[#2A2A2A] p-3.5 rounded-2xl border border-white/5 space-y-2.5">
                <div className="flex items-center justify-between border-b border-white/5 pb-1.5">
                  <div className="flex items-center space-x-1.5 text-xs text-[#F1C40F] font-bold">
                    <Trophy className="w-3.5 h-3.5" />
                    <span className="text-[10px] uppercase font-black tracking-wider">TROPHY CABINET ({allTrophiesCount})</span>
                  </div>
                  <span className="text-[10px] text-white/40 font-mono">
                    {player.totalTrophies} Club • {player.intTrophies?.length || 0} Int.
                  </span>
                </div>

                {allTrophiesCount === 0 ? (
                  <div className="py-4 text-center text-white/40 text-xs italic">
                    No major silverware won during career — built a resilient foundation for the family dynasty!
                  </div>
                ) : (
                  <div className="space-y-1.5 max-h-40 overflow-y-auto pr-1 custom-scrollbar">
                    {/* Club Trophies */}
                    {clubTrophiesWon.map((t, idx) => (
                      <div key={idx} className="bg-[#1E1E1E] p-2 rounded-xl border border-white/5 flex items-center justify-between text-xs">
                        <div className="flex items-center space-x-2">
                          <span className="text-[#F1C40F]">🏆</span>
                          <span className="font-bold text-white">{t.trophy}</span>
                        </div>
                        <div className="text-[10px] text-white/50 font-mono">
                          {t.club} ({t.year})
                        </div>
                      </div>
                    ))}

                    {/* International Trophies */}
                    {(player.intTrophies || []).map((t, idx) => (
                      <div key={`int-${idx}`} className="bg-[#1E1E1E] p-2 rounded-xl border border-cyan-500/20 flex items-center justify-between text-xs">
                        <div className="flex items-center space-x-2">
                          <span className="text-cyan-400">🌍</span>
                          <span className="font-bold text-cyan-300">{t}</span>
                        </div>
                        <div className="text-[10px] text-cyan-400/70 font-mono">
                          {player.nationality}
                        </div>
                      </div>
                    ))}
                  </div>
                )}
              </div>

              {/* 🎖️ CAREER MILESTONES */}
              {milestones.length > 0 && (
                <div className="bg-[#2A2A2A] p-3.5 rounded-2xl border border-white/5 space-y-2">
                  <div className="text-[10px] font-black uppercase text-white/40 tracking-wider font-mono border-b border-white/5 pb-1.5">
                    CAREER MILESTONE BADGES
                  </div>
                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-1.5">
                    {milestones.map((m, idx) => (
                      <div key={idx} className={`p-2 rounded-xl border flex items-start space-x-2 text-xs ${m.color}`}>
                        <span className="text-sm shrink-0">{m.icon}</span>
                        <div>
                          <div className="font-bold text-white text-[11px] leading-tight">{m.label}</div>
                          <div className="text-[9px] text-white/60 leading-tight mt-0.5">{m.desc}</div>
                        </div>
                      </div>
                    ))}
                  </div>
                </div>
              )}
            </div>
          )}

          {/* TAB 3: FINAL STATS & CLUBS */}
          {activeTab === 'stats' && (
            <div className="space-y-3 animate-fade-in">
              {/* DETAILED STATS TABLE */}
              <div className="bg-[#2A2A2A] p-3.5 rounded-2xl border border-white/5 space-y-2.5">
                <div className="text-[10px] font-black uppercase text-white/40 tracking-wider font-mono border-b border-white/5 pb-1.5">
                  FINAL STATISTICAL RECORD
                </div>

                <div className="grid grid-cols-2 sm:grid-cols-4 gap-2 text-center font-mono">
                  <div className="bg-[#1E1E1E] p-2 rounded-xl border border-white/5">
                    <span className="text-[9px] uppercase font-bold text-white/40 block">Appearances</span>
                    <span className="font-bold text-white text-sm">{player.totalApps}</span>
                  </div>
                  <div className="bg-[#1E1E1E] p-2 rounded-xl border border-white/5">
                    <span className="text-[9px] uppercase font-bold text-white/40 block">Goals / Game</span>
                    <span className="font-bold text-[#2ECC71] text-sm">{goalsPerApp}</span>
                  </div>
                  <div className="bg-[#1E1E1E] p-2 rounded-xl border border-white/5">
                    <span className="text-[9px] uppercase font-bold text-white/40 block">Assists / Game</span>
                    <span className="font-bold text-cyan-400 text-sm">{assistsPerApp}</span>
                  </div>
                  <div className="bg-[#1E1E1E] p-2 rounded-xl border border-white/5">
                    <span className="text-[9px] uppercase font-bold text-white/40 block">Goal Involvements</span>
                    <span className="font-bold text-[#F1C40F] text-sm">{goalContributions}</span>
                  </div>
                </div>

                {/* International Record */}
                <div className="bg-[#1E1E1E] p-2.5 rounded-xl border border-white/5 space-y-1.5">
                  <div className="flex items-center justify-between text-xs">
                    <div className="flex items-center space-x-1.5 text-cyan-400 font-bold">
                      <Globe className="w-3.5 h-3.5" />
                      <span>{player.nationality} National Team Record</span>
                    </div>
                    {player.isCaptain && <span className="text-[9px] bg-yellow-500/20 text-yellow-400 px-1.5 py-0.5 rounded font-bold">CAPTAIN</span>}
                  </div>
                  <div className="grid grid-cols-3 gap-1 text-center font-mono text-xs pt-1">
                    <div>
                      <span className="text-[9px] text-white/40 block">Caps</span>
                      <span className="font-bold text-white">{player.intCaps}</span>
                    </div>
                    <div>
                      <span className="text-[9px] text-white/40 block">Int. Goals</span>
                      <span className="font-bold text-cyan-400">{player.intGoals}</span>
                    </div>
                    <div>
                      <span className="text-[9px] text-white/40 block">Int. Trophies</span>
                      <span className="font-bold text-[#F1C40F]">{player.intTrophies?.length || 0}</span>
                    </div>
                  </div>
                </div>
              </div>

              {/* 🛡️ CLUBS REPRESENTED */}
              <div className="bg-[#2A2A2A] p-3.5 rounded-2xl border border-white/5 space-y-2">
                <div className="flex items-center justify-between border-b border-white/5 pb-1.5">
                  <div className="flex items-center space-x-1.5 text-xs text-white/80 font-bold">
                    <Shield className="w-3.5 h-3.5 text-[#2ECC71]" />
                    <span className="text-[10px] uppercase font-black tracking-wider">CLUB JOURNEY & TENURE</span>
                  </div>
                  <span className="text-[10px] text-white/40 font-mono">
                    {clubBreakdown.length || 1} {clubBreakdown.length === 1 ? 'Club' : 'Clubs'}
                  </span>
                </div>

                <div className="space-y-1.5 max-h-36 overflow-y-auto pr-1 custom-scrollbar">
                  {clubBreakdown.length === 0 ? (
                    <div className="bg-[#1E1E1E] p-2.5 rounded-xl border border-white/5 flex items-center justify-between text-xs">
                      <div>
                        <div className="font-bold text-white font-serif italic">{player.club}</div>
                        <div className="text-[10px] text-white/50">{player.totalApps} Apps • {player.totalGoals} Goals</div>
                      </div>
                      <div className="text-[10px] text-[#2ECC71] font-bold">Final Club</div>
                    </div>
                  ) : (
                    clubBreakdown.map((club, idx) => (
                      <div key={idx} className="bg-[#1E1E1E] p-2.5 rounded-xl border border-white/5 flex items-center justify-between text-xs">
                        <div>
                          <div className="font-bold text-white font-serif italic text-xs">{club.clubName}</div>
                          <div className="text-[10px] text-white/50 font-mono space-x-1.5">
                            <span>{club.startYear}–{club.endYear} ({club.seasons} yrs)</span>
                            <span>•</span>
                            <span>{club.apps} apps</span>
                            <span>•</span>
                            <span className="text-[#2ECC71]">{club.goals} goals</span>
                            {club.trophies.length > 0 && (
                              <span className="text-[#F1C40F]"> • {club.trophies.length} 🏆</span>
                            )}
                          </div>
                        </div>
                        {idx === clubBreakdown.length - 1 && (
                          <span className="text-[9px] font-bold uppercase px-1.5 py-0.5 rounded bg-white/10 text-white/70">
                            Final
                          </span>
                        )}
                      </div>
                    ))
                  )}
                </div>
              </div>

              {/* 🧬 INHERITED TRAITS FOR GENERATION N+1 */}
              {player.traits && player.traits.length > 0 && (
                <div className="bg-[#2A2A2A] p-3.5 rounded-2xl border border-white/5 space-y-2">
                  <div className="text-[10px] font-black uppercase text-white/40 tracking-wider font-mono border-b border-white/5 pb-1.5">
                    HERITAGE TRAITS PASSING TO GEN {player.generation + 1}
                  </div>
                  <div className="flex flex-wrap gap-1.5">
                    {player.traits.map(trait => (
                      <span
                        key={trait.id}
                        className="text-[10px] px-2.5 py-1 rounded-lg border font-bold bg-[#1E1E1E]"
                        style={{ borderColor: trait.color, color: trait.color }}
                      >
                        ⚡ {trait.name}
                      </span>
                    ))}
                  </div>
                </div>
              )}
            </div>
          )}

        </div>

        {/* 🚀 ACTION FOOTER */}
        <div className="pt-2 border-t border-white/10 shrink-0 space-y-2">
          <button
            onClick={handleProceed}
            className="w-full bg-[#F1C40F] hover:bg-[#f39c12] text-black font-black text-xs py-3.5 rounded-2xl transition-all active:scale-[0.98] flex items-center justify-center space-x-2 uppercase tracking-wider cursor-pointer shadow-lg shadow-[#F1C40F]/20"
          >
            <UserPlus className="w-4 h-4 fill-current" />
            <span>CONFIRM & BIRTH GENERATION {player.generation + 1} CHILD</span>
          </button>

          {onClose && (
            <button
              onClick={onClose}
              className="w-full bg-transparent hover:bg-white/5 text-white/60 hover:text-white text-xs py-2 rounded-xl transition-colors font-semibold flex items-center justify-center space-x-1 cursor-pointer"
            >
              <span>Return to Career Overview</span>
            </button>
          )}
        </div>

      </div>
    </div>
  );
};
